<?php

namespace ContainerLKgBCou;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5eYkN6Y.App\Controller\ClientController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5eYkN6Y.App\\Controller\\ClientController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.errored..service_locator.5eYkN6Y.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.5eYkN6Y": it needs an instance of "App\\Entity\\Client" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'client' => 'App\\Entity\\Client',
        ]))->withContext('App\\Controller\\ClientController::show()', $container);
    }
}
