<?php

namespace ContainerD61bu66;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XgV966x.App\Controller\ClientController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XgV966x.App\\Controller\\ClientController::delete()'] = ($container->privates['.service_locator.XgV966x'] ?? $container->load('get_ServiceLocator_XgV966xService'))->withContext('App\\Controller\\ClientController::delete()', $container);
    }
}
