<?php

namespace ContainerSwR2RVv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H4LJNQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h4_LJNQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.DbhFNW6.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.5eYkN6Y.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.DbhFNW6.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.5eYkN6Y.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:delete' => '?',
        ]);

        if (isset($container->privates['.service_locator.h4_LJNQ'])) {
            return $container->privates['.service_locator.h4_LJNQ'];
        }

        return $container->privates['.service_locator.h4_LJNQ'] = $instance;
    }
}
