<?php

namespace ContainerSwR2RVv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XgV966xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XgV966x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.errored..service_locator.XgV966x.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.XgV966x": it needs an instance of "App\\Entity\\Client" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'client' => 'App\\Entity\\Client',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.XgV966x'])) {
            return $container->privates['.service_locator.XgV966x'];
        }

        return $container->privates['.service_locator.XgV966x'] = $instance;
    }
}
