<?php

namespace ContainerTR15zeL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaticControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StaticController' shared autowired service.
     *
     * @return \App\Controller\StaticController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StaticController.php';

        $container->services['App\\Controller\\StaticController'] = $instance = new \App\Controller\StaticController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\StaticController', $container));

        return $instance;
    }
}
