<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOx3ZO5R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOx3ZO5R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOx3ZO5R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOx3ZO5R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOx3ZO5R\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ox3ZO5R',
    'container.build_id' => '2d7c0813',
    'container.build_time' => 1769608791,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOx3ZO5R');
