<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLKgBCou\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLKgBCou/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLKgBCou.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLKgBCou\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLKgBCou\App_KernelDevDebugContainer([
    'container.build_hash' => 'LKgBCou',
    'container.build_id' => 'fb10fb05',
    'container.build_time' => 1768396224,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLKgBCou');
